### ISSUE TITLE
Invalid parameters. discover: boolean value expected

### ISSUE THREAD

**Issue by chucknwest** [webfolderio/cdp4j#104]
When I try running the sample Bing.java and several others with the latest code from master I get this error:

Exception in thread "main" io.webfolder.cdp.exception.CommandException: Invalid parameters. discover: boolean value expected
at io.webfolder.cdp.session.WSAdapter.lambda$0(WSAdapter.java:116)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)

**Comment by webfolderio** [comment]
Hi @chucknwest 

If you are using Eclipse, please enable the "Store information about method parameters" feature under the Properties -> Java Compiler -> Classfile Generation

**Comment by chucknwest** [comment]
Thanks! That fixed the problem.

**Comment by hubo9624963** [comment]
the same problem exists in idea
but i could not find the enable option

**Comment by webfolderio** [comment]
@hubo9624963 

https://stackoverflow.com/questions/39217830/how-to-use-parameters-javac-option-in-intellij
