### ISSUE TITLE
Launcher#launch#[ERROR]WebSocket connection url is required

### ISSUE THREAD

**Issue by BOFA1ex** [webfolderio/cdp4j#128]
Example
```java
        Launcher launcher = new Launcher();
        try (SessionFactory factory = launcher.launch();
             Session session = factory.create()) {
            session
                    .navigate("https://webfolder.io")
                    .waitDocumentReady();

            String title = session.getText("//title");

            System.out.println(title);
        } finally {
            launcher.kill();
        }
```
```
#Stacktrace
Exception in thread "main" io.webfolder.cdp.exception.CdpException: WebSocket connection url is required!
	at io.webfolder.cdp.Launcher.launchWithProcessBuilder(Launcher.java:308)
	at io.webfolder.cdp.Launcher.launch(Launcher.java:247)
	at com.bofa.QrCodeAction.main(QrCodeAction.java:41)
```
it return false immediately in while-loop.
but the browser is already launch, how to solve this problem.

#Process#arguments
![image](https://user-images.githubusercontent.com/30573693/88907041-c293b000-d28a-11ea-9ece-6e6d8f36f966.png)

```java
Launch#launchWithProcessBuilder
            try (Scanner scanner = new Scanner(process.getErrorStream())) {
                /* return false immediately. */
                while (scanner.hasNext()) {
                    String line = scanner.nextLine().trim();
                    if (line.isEmpty()) {
                        continue;
                    }
                    if (line.toLowerCase(ENGLISH).startsWith("devtools listening on")) {
                        int start = line.indexOf("ws://");
                        connection = new WebSocketConnection(line.substring(start, line.length()));
                        break;
                    }
                }
                if (connection == null) {
                    throw new CdpException("WebSocket connection url is required!");
                }
            }
```

**Comment by webfolderio** [comment]
Could you please let me know which version cdp4j do you use?

**Comment by BOFA1ex** [comment]
```xml
        <properties>
              <cdp4j.version>4.2.2</cdp4j.version>
        </properties>
        <dependency>
            <groupId>io.webfolder</groupId>
            <artifactId>cdp4j</artifactId>
            <version>${cdp4j.version}</version>
        </dependency>
```
![image](https://user-images.githubusercontent.com/30573693/88916251-55871700-d298-11ea-9b4c-28df03e8acf1.png)

**Comment by ngdaddikar** [comment]
I am facing the same error but I am not sure what the cause is. What's the solution?

**Comment by BOFA1ex** [comment]
> I am facing the same error but I am not sure what the cause is. What's the solution?

check your hostname, make sure is edited in /etc/hosts. such as xx-mini.local
if not exists in /etc/hosts, try to write it like below.
```
127.0.0.1       localhost       bofa1ex-mini.local
::1             localhost       bofa1ex-mini.local
```
it works for me.
