### ISSUE TITLE
Can't delete user profile directories after finishing execution.

### ISSUE THREAD

**Issue by abozanona** [webfolderio/cdp4j#139]
I'm implementing the sample java application for generating PDF files in parallel.

```
    private static void chromePrinting(String pagePath, String token) throws IOException {
        Path file = createTempFile("pdf-" + pagePath, ".pdf");
        final String PROFILES_DIRECTORY = "C:\\Users\\User\\Desktop\\dev_chrome_profile\\";

        String profilePath = PROFILES_DIRECTORY + "profile-" + vin + "-" + UUID.randomUUID().toString();

        Options options = Options.builder()
                // https://blog.apify.com/how-to-make-headless-chrome-and-puppeteer-use-a-proxy-server-with-authentication-249a21a79212
                // .arguments(Collections.singletonList("--proxy-server=http://username:password@myserver.com:9090"))
                .headless(true)
                .userDataDir(Paths.get(profilePath))
                .build();

        Launcher launcher = new Launcher(options);

        try (SessionFactory factory = launcher.launch(); Session session = factory.create()) {

            Network network = session.getCommand().getNetwork();
            CookieParam param = new CookieParam();
            param.setDomain("www.example.com");
            param.setName("_token");
            param.setValue(token);

            network.setCookies(Collections.singletonList(param));

            session.navigate("https://www.example.com/pdf/report?pagePath=" + pagePath);
            session.waitDocumentReady();

            PrintToPDFResult result = session.getCommand().getPage().printToPDF(false, true, true, null, null, null, null, null, null, null, null, null, null, null, null, null);
            byte[] content = Base64.getDecoder().decode(result.getData());
            result.getData();
            write(file, content);
            session.getCommand().getPage().close();
            FileUtils.deleteDirectory(new File(profilePath));

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            launcher.kill();
        }
    }
```

But I'm getting this error

```
java.io.IOException: Unable to delete file: C:\Users\User\Desktop\dev_chrome_profile\profile-randompath-b0aadab8-938b-4a73-8547-a7d71ea9e21b\Default\Session Storage\MANIFEST-000001
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2381)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1679)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1575)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2372)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1679)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1575)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2372)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1679)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1575)
	at com.code.test.Main.chromePrinting(Main.java:122)
	at com.code.test.Main.lambda$main$0(Main.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

How can I remove the lock on user profile directory and delete it?

**Comment by webfolderio** [comment]
Please make sure that chrome process is terminated before deleting user profile directory.

**Comment by abozanona** [comment]
How can I terminate the chrome process?
