### ISSUE TITLE
windows10 Can't kill task

### ISSUE THREAD

**Issue by 149456275** [webfolderio/cdp4j#141]
google:88.0.4324.96
server:10.0.18363.1256
jdk:8.0.241

this code:

Options options = Options.builder().headless(true).userDataDir(tempPath).build();
        Launcher launcher = new Launcher(options);
        SessionFactory factory = launcher.launch();
        try {
        	try (Session session = factory.create()) {
                session.navigate(path);
                session.waitDocumentReady();
                
                String s = session.callFunction("111", String.class);
                System.out.println(s);
                //session.evaluate(expression)
            }
            factory.close();
        }finally {
        	launcher.kill(); 
}

run end 

C:\Users\Administrator>tasklist /fi "imagename eq chrome.exe" /fi "sessionname eq Console"
映像名称                       PID 会话名              会话#       内存使用
========================= ======== ================ =========== ============
chrome.exe                   22612 Console                    1     45,496 K
chrome.exe                   33172 Console                    1      6,728 K
chrome.exe                   36152 Console                    1      6,596 K
chrome.exe                    8056 Console                    1     29,092 K
chrome.exe                   36924 Console                    1     17,416 K

**Comment by zghnx** [comment]
有没有遇到?
Exception in thread "Thread-0" io.webfolder.cdp.exception.CdpException: WebSocket connection url is required!
	at io.webfolder.cdp.Launcher.launchWithProcessBuilder(Launcher.java:346)
	at io.webfolder.cdp.Launcher.launch(Launcher.java:284)

**Comment by 149456275** [comment]
没遇见过，你是在做什么东西的时候引发的呢？------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月1日(星期四) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [webfolderio/cdp4j] windows10 Can&#39;t kill task (#141)
