### ISSUE TITLE
Occasional exception io.webfolder.cdp.exception.CommandException: No node with given id found

### ISSUE THREAD

**Issue by suzukieng** [webfolderio/cdp4j#142]
I'm trying to use cdp4j to monitor an authentication flow.

The sequence of commands I use is:

```
        cdpSession.navigateAndWait(loginUrl, WaitUntil.DomReady, 10000);
```

and then a little later:

```
        return cdpSession.waitUntil(session -> {
            String content = session.getContent();
            return content.contains("Some string I'm checking");
        }, 30000);
```

I occassionally (about 1 in 10) get the following exception from cdp4j:

```
io.webfolder.cdp.exception.CommandException: No node with given id found
	at io.webfolder.cdp.session.MessageHandler.lambda$process$1(MessageHandler.java:99)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

I don't use any IDs anywhere. Any idea where this might be coming from?

**Comment by suzukieng** [comment]
I'm using the latest cdp4j version 4.2.2 by the wy.

**Comment by webfolderio** [comment]
Hi @suzukieng , sorry for the late response. Please send us your code snippet. If you have a commercial license & support, we will respond in 2 business days.

**Comment by Alewhjb** [comment]
I also encountered a similar problem
