### ISSUE TITLE
WebSocket connection url is required!

### ISSUE THREAD

**Issue by xhw168** [webfolderio/cdp4j#144]
Exception in thread "main" io.webfolder.cdp.exception.CdpException: WebSocket connection url is required!
	at io.webfolder.cdp.Launcher.launchWithProcessBuilder(Launcher.java:346)
	at io.webfolder.cdp.Launcher.launch(Launcher.java:284)

**Comment by Budroid** [comment]
I had the same problem when not running in headless mode. Are you running in headless mode?
