### ISSUE TITLE
Getting Invalid parameters. fitWindow: boolean value expected

### ISSUE THREAD

**Issue by castortech** [webfolderio/cdp4j#43]
Running the Screenshot example I get this error:
Exception in thread "main" io.webfolder.cdp.exception.CommandException: Invalid parameters. fitWindow: boolean value expected
	at io.webfolder.cdp.session.WSAdapter.lambda$onTextMessage$1(WSAdapter.java:127)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

While doing some test with headless I ended up with the same error after calling Emulation#setDeviceMetricsOverride which doesn't take the fitWindow argument. 

So for now I am using the Page#setDeviceMetricsOverride instead but I am a bit clueless about the difference.

**Comment by webfolderio** [comment]
Hi @castortech 

Current api is compitable with latest Chrome (canary).

Please see the similar issue: https://github.com/webfolderio/cdp4j/issues/24

**Comment by castortech** [comment]
Thanks for the info
