### ISSUE TITLE
Problem with FollowRedirects sample

### ISSUE THREAD

**Issue by valentyn-hrynevich** [webfolderio/cdp4j#73]
Hello everybody, I have a problem. 
When i trying to run https://github.com/webfolderio/cdp4j/blob/master/src/test/java/io/webfolder/cdp/sample/FollowRedirects.java example, but received following error
```
Exception in thread "main" io.webfolder.cdp.exception.CommandException: 'Network.setRequestInterception' wasn't found
	at io.webfolder.cdp.session.WSAdapter.lambda$onTextMessage$1(WSAdapter.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Do you know how to fix that?

**Comment by webfolderio** [comment]
Please make sure that you are using latest Chrome version.

**Comment by valentyn-hrynevich** [comment]
I'm using Google chrome 63.0.3239.132.

**Comment by webfolderio** [comment]
`setRequestInterception` is not supported by Chrome 63. Update your Chrome version to 64.
