### ISSUE TITLE
io.webfolder.cdp.exception.CommandException when enable the network

### ISSUE THREAD

**Issue by paine1690** [webfolderio/cdp4j#8]
Exception in thread "cpd4j-8" io.webfolder.cdp.exception.CommandException: Invalid parameters. interceptionId: string value expected
	at io.webfolder.cdp.session.WSAdapter.lambda$0(WSAdapter.java:126)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "cpd4j-2" io.webfolder.cdp.exception.CommandException: Invalid parameters. interceptionId: string value expected
	at io.webfolder.cdp.session.WSAdapter.lambda$0(WSAdapter.java:126)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "cpd4j-22" io.webfolder.cdp.exception.CommandException: Invalid parameters. interceptionId: string value expected
	at io.webfolder.cdp.session.WSAdapter.lambda$0(WSAdapter.java:126)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by webfolderio** [comment]
Hi @paine1690,

Could you please send me a test to produce this error.

**Comment by paine1690** [comment]
@webfolderio 
here is my code
`  public static void main(String[] args) throws IOException {
    Launcher launcher = new Launcher();

    try (SessionFactory factory = launcher.launch(new ArrayList<String>(Arrays.asList("--headless", "--disable-gpu")));
                        Session session = factory.create()) {
               
        Network network = session.getCommand().getNetwork();      
        network.enable();

        session.addEventListener((e, d) -> {
          if (NetworkResponseReceived.equals(e)) {
            ResponseReceived rr = (ResponseReceived) d;
            String requestId = rr.getRequestId();
            //System.out.println(requestId);
            GetResponseBodyResult rb = network.getResponseBody(requestId);              
          } 
        });
        session.navigate("http://www.baidu.com"); 
        session.wait(10000);
        
        Path file = createTempFile("screenshot", ".png");
        session.activate();
        byte[] data = session.captureScreenshot();
        write(file, data);
        if (isDesktopSupported()) {
          getDesktop().open(file.toFile());
      }
        
    } finally{
      System.out.println("end");
    }
  }`
and I find it is caused by 
GetResponseBodyResult rb = network.getResponseBody(requestId);
