### ISSUE TITLE
ERROR Missing or invalid 'browserContextId' parameter

### ISSUE THREAD

**Issue by hajderr** [webfolderio/cdp4j#83]
Just cloned the project, imported into my IDE and tried to run a test but got the error

```16:16:41.372 [main] ERROR Missing or invalid 'browserContextId' parameter
io.webfolder.cdp.exception.CommandException: Missing or invalid 'browserContextId' parameter
	at io.webfolder.cdp.session.WSAdapter.lambda$onTextMessage$1(WSAdapter.java:122) ~[classes/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
Exception in thread "main" io.webfolder.cdp.exception.CommandException: Missing or invalid 'url' parameter
	at io.webfolder.cdp.session.WSAdapter.lambda$onTextMessage$1(WSAdapter.java:122)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Disconnected from the target VM, address: '127.0.0.1:35513', transport: 'socket'
```

**Comment by webfolderio** [comment]
IDE & Version?

**Comment by hajderr** [comment]
IntelliJ 2017

**Comment by hajderr** [comment]
*bump* anyone can confirm?

**Comment by hajderr** [comment]
`$> mvn test`

 from terminal fixes the problem. Triggering Build Project inside IntelliJ does not.
