### ISSUE TITLE
Cannot find context with specified id

### ISSUE THREAD

**Issue by argenumsky** [webfolderio/cdp4j#86]
I am seeing this errors when executing a script to navigate to a new URL:

```java

Exception in thread "cdp4j-15" io.webfolder.cdp.exception.CommandException: Cannot find context with specified id
	at io.webfolder.cdp.session.WSAdapter.lambda$onTextMessage$1(WSAdapter.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

...

Exception in thread "cdp4j-8" io.webfolder.cdp.exception.CommandException: Cannot find context with specified id
	at io.webfolder.cdp.session.WSAdapter.lambda$onTextMessage$1(WSAdapter.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

What could be the cause of this error?

**Comment by webfolderio** [comment]
Please try to test again with version 3.0.3
