### ISSUE TITLE
Sizzle--CommandException: Could not find node with given ID

### ISSUE THREAD

**Issue by tylr2017** [webfolderio/cdp4j#92]
What is the reason for the occasional "io.webfolder.cdp.exception.CommandException: Could not find node with given ID" error when I enabled Sizzle Selector in session? Has anyone ever met this situation? The error log is as follows:
io.webfolder.cdp.exception.CommandException: Could not find node with given id
	at io.webfolder.cdp.session.WSAdapter.lambda$onTextMessage$1(WSAdapter.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Please help me.Thanks!

**Comment by webfolderio** [comment]
What is your cdp4j version? Could you please try to use version `3.0.0-SNAPSHOT`

**Comment by tylr2017** [comment]
My cdp4j version is 2.2.4
