### ISSUE TITLE
NPE in Session.java:317 version 3.0.0

### ISSUE THREAD

**Issue by tasqon** [webfolderio/cdp4j#94]
`java.lang.NullPointerException
	at io.webfolder.cdp.session.Session.navigate(Session.java:317)

`works fine through a number of html files and then jump out with this NPE

**Comment by webfolderio** [comment]
Hi @tasqon, Could you please share a sample code to produce error?

Thanks

**Comment by tasqon** [comment]
` 
            
            Launcher launcher = new Launcher();
            SessionFactory factory = launcher.launch();

            ArrayList<String> reviewHtmls = new ArrayList<>();

            String kununuHtml = "https://www.kununu.com/de/sixt-autovermietung/kommentare";

            boolean hasNextHtml = true;

            Session session = factory.create();
            while (hasNextHtml) {
                session.navigate(kununuHtml);
                session.waitDocumentReady(15000);
                session.wait(2000);
                content = session.getContent();
                document = Jsoup.parse(content);

                Elements paginations = document.select("body > main > div.container-fluid > div.company-profile-container > section > div.row > div > div.paginationControl > a");
                if (!paginations.isEmpty()) {
                    kununuHtml = kununuHomeHtml + paginations.attr("href");
                } else {
                    hasNextHtml = false;
                }

                Elements articles = document.getElementsByTag("article");
                Iterator<Element> articlesIterator = articles.iterator();

                while (articlesIterator.hasNext()) {
                    Element article = articlesIterator.next();
                    System.out.println("********* " + kununuHomeHtml + readReviewUrl(article));
                    reviewHtmls.add(kununuHomeHtml + readReviewUrl(article));
                }
            }

            Iterator<String> reviewHtmlsIterator = reviewHtmls.iterator();
            while (reviewHtmlsIterator.hasNext()) {
                String reviewHtml = reviewHtmlsIterator.next();
                session.navigate(reviewHtml);
                session.waitDocumentReady(20000);
                session.wait(2000);
                content = session.getContent();
                document = Jsoup.parse(content);

                Elements reviewArticles = document.getElementsByTag("article");
                if (!reviewArticles.isEmpty()) {
                    Element reviewArticle = reviewArticles.first();
                    htmlWriter.write(reviewArticle.outerHtml());
                    Review review = readReview(reviewArticle);
                    csvWriter.write(review, header, processors);
                }
            }

            session.close();
`

**Comment by amondnet** [comment]
I have same problem. 
```
java.lang.NullPointerException: null at io.webfolder.cdp.session.Session.navigateAndWait(Session.java:342)
```
